FROM postgres:17.4

WORKDIR /bd

#COPY backend/pyproject.toml backend/
#COPY backend/uv.lock backend/
#
#COPY db_lib/pyproject.toml db_lib/
#COPY db_lib/uv.lock db_lib/
#
##RUN apt-get update && apt-get install -y curl \
##    && rm -rf /var/lib/apt/lists/*
#RUN curl -LsSf https://astral.sh/uv/install.sh | sh
#
#RUN uv sync --directory backend/ --active
#RUN uv sync --directory db_lib/ --active
#
#COPY . .
#
#ENV FLASK_APP=backend/app.py

RUN apt-get update && apt-get install -y netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

COPY init_db.sh .

EXPOSE 5432

CMD ["bash", "init_db.sh"]