"""Update exp_date

Revision ID: 6a1159be3cf1
Revises: 508aa7d601fd
Create Date: 2025-03-08 18:33:23.268408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a1159be3cf1'
down_revision: Union[str, None] = '508aa7d601fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'exp_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'exp_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
