[project]
name = "db-lib"
version = "0.1.0"
description = ""
requires-python = "==3.12.9"
authors = [
    {name = "ykozhanov", email = "ykozhanov97@gmail.com" }
]
dependencies = [
    "sqlalchemy==2.0.36",
    "psycopg2==2.9.10",
]
