[project]
name = "db-lib"
version = "0.1.0"
description = ""
requires-python = "==3.12.9"
authors = [
    {name = "ykozhanov", email = "ykozhanov97@gmail.com" }
]
dependencies = [
    "alembic==1.14.0",
    "python-dotenv==1.0.1"
]
